apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  members:
    - bookinfo-qa
